-- CreateTable
CREATE TABLE `FitUsuario` (
    `N_ID_USUARIO` INTEGER NOT NULL AUTO_INCREMENT,
    `N_ID_PLAN` INTEGER NULL,
    `X_NOMBRE` VARCHAR(100) NULL,
    `X_APELLIDO` VARCHAR(100) NULL,
    `X_EMAIL` VARCHAR(100) NULL,
    `X_CONTRASENA` VARCHAR(100) NULL,
    `X_DIRECCION` VARCHAR(255) NULL,
    `X_TELEFONO` VARCHAR(20) NULL,
    `F_REGISTRO` DATETIME(3) NULL,
    `X_CODIGO_VERIFICACION` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`N_ID_USUARIO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
